site_name: Fast Web Help
site_url: https://jastuccio.github.io/fast-web-help

nav:
  - Home: index.md
  - Services: services.md
  - Portfolio: portfolio.md
  - Contact: contact.md

theme:
  name: blacksun